import './style.css'
import { createClient } from '@supabase/supabase-js'

const url = import.meta.env.VITE_SUPABASE_URL || 'https://ocnedejiwcvqjiacwbic.supabase.co'
const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_h4k4MGUIdFiu-Vjk4hKlrg_gGsqUcOz'
const supabase = key ? createClient(url, key) : null

const root = document.querySelector<HTMLDivElement>('#root')!
let user: any = null
let page = 'home'

const esc = (s:string) => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
const nav = (p:string) => { page=p; render() }
const toast = (message:string,bad=false) => { const x=document.createElement('div'); x.className='toast'+(bad?' bad':''); x.textContent=message; document.body.appendChild(x); setTimeout(()=>x.remove(),3000) }

function landing(){
  root.innerHTML = `
  <div class="landing">
    <nav><div class="brand"><b>◆</b> Bid<span>Bidder</span></div><div><button class="btn ghost" id="login">Log in</button> <button class="btn primary" id="signup">Get started</button></div></nav>
    <section class="hero"><div><small>AI-POWERED BID DISCOVERY</small><h1>Find bids.<br><em>Win more business.</em></h1><p>BidBidder helps businesses discover opportunities, match with the right bids, and stay on top of every application with an AI assistant.</p><div class="hero-actions"><button class="btn primary big" id="heroSignup">Start finding bids →</button></div><small>No complicated setup. Built for growing businesses.</small></div>
    <div class="hero-card"><div class="mini-head"><b>AI Match Center</b><span class="live">● LIVE</span></div><div class="match"><div><b>Transportation Services</b><small>State & Local</small></div><strong>96%</strong></div><div class="match"><div><b>Medical Supply Contract</b><small>Healthcare</small></div><strong>91%</strong></div><div class="match"><div><b>School Transportation</b><small>Education</small></div><strong>87%</strong></div><div class="ai-tip">✦ <span>AI Agent: I found 3 opportunities that fit your business.</span></div></div></section>
    <section class="features"><div><span>01</span><h3>Smart matching</h3><p>Find opportunities aligned with your services and locations.</p></div><div><span>02</span><h3>AI bid agent</h3><p>Get guidance through research, applications and next steps.</p></div><div><span>03</span><h3>Stay organized</h3><p>Track saved bids, applications and deadlines in one place.</p></div><div><span>04</span><h3>Real-time alerts</h3><p>Get notified when new opportunities and application activity arrive.</p></div></section>
    <footer>© 2026 BidBidder. Find. Match. Win.</footer></div>`
  document.querySelectorAll('#login').forEach(b=>b.addEventListener('click',()=>auth(false)))
  document.querySelectorAll('#signup,#heroSignup').forEach(b=>b.addEventListener('click',()=>auth(true)))
}
function auth(signup=false){
 root.innerHTML=`<div class="auth"><div class="auth-box"><div class="brand center"><b>◆</b> Bid<span>Bidder</span></div><h1>${signup?'Create your account':'Welcome back'}</h1><p>${signup?'Start finding better opportunities.':'Sign in to your BidBidder account.'}</p>${signup?'<input id="name" placeholder="Your name"><input id="company" placeholder="Company name">':''}<input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password"><button class="btn primary full" id="submit">${signup?'Create account':'Log in'}</button><button class="text-btn" id="back">← Back</button><div id="msg"></div></div></div>`
 document.querySelector('#back')!.addEventListener('click',landing)
 document.querySelector('#submit')!.addEventListener('click',async()=>{
  const msg=document.querySelector('#msg')!; if(!supabase){msg.innerHTML='<div class="error">Supabase connection key is not configured yet.</div>';return}
  const email=(document.querySelector('#email') as HTMLInputElement).value.trim(), password=(document.querySelector('#password') as HTMLInputElement).value
  try{
   if(signup){ const name=(document.querySelector('#name') as HTMLInputElement).value.trim(), company=(document.querySelector('#company') as HTMLInputElement).value.trim(); const r=await supabase.auth.signUp({email,password,options:{data:{full_name:name,company_name:company}}}); if(r.error) throw r.error; msg.innerHTML='<div class="success">Account created. Check your email if confirmation is required.</div>'; if(r.data.session){user=r.data.user;nav('dashboard')} }
   else {const r=await supabase.auth.signInWithPassword({email,password}); if(r.error)throw r.error; user=r.data.user;nav('dashboard')}
  }catch(e:any){msg.innerHTML='<div class="error">'+esc(e.message||'Something went wrong')+'</div>'}
 })
}
async function dashboard(){
 let counts={bids:0,apps:0,saved:0,notes:0}
 if(supabase&&user){const [a,b,c,d]=await Promise.all([supabase.from('bid_opportunities').select('*',{count:'exact',head:true}).eq('status','open'),supabase.from('bid_applications').select('*',{count:'exact',head:true}).eq('user_id',user.id),supabase.from('saved_opportunities').select('*',{count:'exact',head:true}).eq('user_id',user.id),supabase.from('notifications').select('*',{count:'exact',head:true}).eq('user_id',user.id).is('read_at',null)]);counts={bids:a.count||0,apps:b.count||0,saved:c.count||0,notes:d.count||0}}
 root.innerHTML=`<div class="app"><aside><div class="brand"><b>◆</b> Bid<span>Bidder</span></div><button class="nav active" data-p="dashboard">⌂ Dashboard</button><button class="nav" data-p="bids">◈ Find Bids</button><button class="nav" data-p="saved">☆ Saved</button><button class="nav" data-p="applications">✓ Applications</button><button class="nav" data-p="agent">✦ AI Bid Agent</button><button class="nav" data-p="notifications">♢ Notifications <i>${counts.notes}</i></button><div class="sidebottom"><button class="nav" data-p="support">? Help & Support</button><button class="nav" id="signout">↪ Sign out</button></div></aside><main><header><b>Dashboard</b><span>Welcome back</span></header><section class="page"><div class="welcome"><div><small>YOUR BIDBIDDER COMMAND CENTER</small><h1>Let's win some business.</h1><p>Here is what is happening with your opportunities.</p></div><button class="btn primary" data-p="bids">Find new bids →</button></div><div class="stats"><div><small>Open opportunities</small><strong>${counts.bids}</strong></div><div><small>Applications</small><strong>${counts.apps}</strong></div><div><small>Saved bids</small><strong>${counts.saved}</strong></div><div><small>Unread alerts</small><strong>${counts.notes}</strong></div></div><div class="grid"><div class="card"><h2>AI Bid Agent</h2><p>Your AI assistant can help you find matches and decide what to do next.</p><button class="btn dark" data-p="agent">Ask the AI Agent →</button></div><div class="card dark"><h2>Ready to find your next opportunity?</h2><p>Search the marketplace and start building your pipeline.</p><button class="btn primary" data-p="bids">Explore bids</button></div></div></section></main></div>`
 bindNav(); document.querySelector('#signout')!.addEventListener('click',async()=>{await supabase?.auth.signOut();user=null;landing()})
}
function simple(p:string,title:string,body:string){root.innerHTML=`<div class="app"><aside><div class="brand"><b>◆</b> Bid<span>Bidder</span></div><button class="nav" data-p="dashboard">⌂ Dashboard</button><button class="nav" data-p="bids">◈ Find Bids</button><button class="nav" data-p="saved">☆ Saved</button><button class="nav" data-p="applications">✓ Applications</button><button class="nav" data-p="agent">✦ AI Bid Agent</button><button class="nav" data-p="notifications">♢ Notifications</button><div class="sidebottom"><button class="nav" data-p="support">? Help & Support</button><button class="nav" id="signout">↪ Sign out</button></div></aside><main><header><b>${title}</b><span>BidBidder</span></header><section class="page"><div class="pageintro"><small>BUSINESS GROWTH CENTER</small><h1>${title}</h1><p>${body}</p></div><div class="card" id="content">Loading...</div></section></main></div>`;bindNav();document.querySelector('#signout')!.addEventListener('click',async()=>{await supabase?.auth.signOut();user=null;landing()});loadContent(p)}
function bindNav(){document.querySelectorAll<HTMLElement>('[data-p]').forEach(x=>x.addEventListener('click',()=>nav(x.dataset.p!)))}
async function loadContent(p:string){const c=document.querySelector('#content');if(!c)return
 if(!supabase||!user){c.innerHTML='<p>Connect your Supabase environment to use live data.</p>';return}
 if(p==='bids'){const r=await supabase.from('bid_opportunities').select('*').eq('status','open').limit(50);c.innerHTML='<input id="q" placeholder="Search opportunities..."><div id="list">'+(r.data||[]).map((x:any)=>'<article class="card opp" data-id="'+esc(x.id)+'"><div><b>'+esc(x.title||x.name||'Opportunity')+'</b><p>'+esc(x.description||'')+'</p><small>'+esc(x.category||'')+' · '+esc(x.location||'')+'</small></div><div class="opp-actions"><button class="btn primary apply" data-id="'+esc(x.id)+'">Start application</button><button class="btn ghost save" data-id="'+esc(x.id)+'">☆ Save</button></div></article>').join('')+'</div>';document.querySelector('#q')?.addEventListener('input',e=>{const q=(e.target as HTMLInputElement).value.toLowerCase();document.querySelectorAll('article').forEach(a=>(a as HTMLElement).style.display=a.textContent!.toLowerCase().includes(q)?'block':'none')});document.querySelectorAll<HTMLButtonElement>('.save').forEach(b=>b.addEventListener('click',async()=>{const x=await supabase.from('saved_opportunities').upsert({user_id:user.id,opportunity_id:b.dataset.id});toast(x.error?x.error.message:'Opportunity saved.')}));document.querySelectorAll<HTMLButtonElement>('.apply').forEach(b=>b.addEventListener('click',async()=>{const existing=await supabase.from('bid_applications').select('id').eq('user_id',user.id).eq('opportunity_id',b.dataset.id).maybeSingle();if(existing.data){toast('You already started this application.');return}const x=await supabase.from('bid_applications').insert({user_id:user.id,opportunity_id:b.dataset.id,status:'planning'});toast(x.error?x.error.message:'Application started.');if(!x.error)setTimeout(()=>nav('applications'),300)}))}
 else if(p==='agent'){c.innerHTML='<div class="chat"><div class="bubble">Hi! I’m your BidBidder AI Agent. Ask me which opportunities fit your business, what to apply for, or what to do next.</div></div><form id="ask"><input id="msg" placeholder="Ask your AI Bid Agent..."><button class="btn primary">Send</button></form>';document.querySelector('#ask')!.addEventListener('submit',async e=>{e.preventDefault();const m=(document.querySelector('#msg') as HTMLInputElement).value.trim();if(!m)return;const chat=document.querySelector('.chat')!;chat.innerHTML+='<div class="bubble user">'+esc(m)+'</div>';const r=await supabase.functions.invoke('bid-agent',{body:{message:m}});chat.innerHTML+='<div class="bubble">'+esc(r.data?.answer||r.error?.message||'I could not complete that request.')+'</div>'; (document.querySelector('#msg') as HTMLInputElement).value=''})}
 else if(p==='support'){c.innerHTML='<form id="support"><input id="subject" placeholder="Subject"><textarea id="description" rows="6" placeholder="How can we help?"></textarea><button class="btn primary">Send support request</button><div id="msg"></div></form>';document.querySelector('#support')!.addEventListener('submit',async e=>{e.preventDefault();const r=await supabase.from('support_requests').insert({user_id:user.id,subject:(document.querySelector('#subject') as HTMLInputElement).value,message:(document.querySelector('#description') as HTMLTextAreaElement).value});document.querySelector('#msg')!.innerHTML=r.error?'<div class="error">'+esc(r.error.message)+'</div>':'<div class="success">Request sent.</div>'})}
 else {const table=p==='saved'?'saved_opportunities':p==='applications'?'bid_applications':'notifications';const r=await supabase.from(table).select('*').limit(50);c.innerHTML='<table><tbody>'+(r.data||[]).map((x:any)=>'<tr><td><b>'+esc(x.title||x.status||x.message||'Activity')+'</b></td><td>'+esc(x.created_at||'')+'</td></tr>').join('')+'</tbody></table>'}
}
async function render(){if(!user){landing();return} if(page==='dashboard')await dashboard();else if(page==='bids')simple('bids','Find Bids','Discover opportunities matched to your business.');else if(page==='saved')simple('saved','Saved Bids','Keep promising opportunities in one place.');else if(page==='applications')simple('applications','Applications','Track every bid you have started or submitted.');else if(page==='agent')simple('agent','AI Bid Agent','Your always-on assistant for bid discovery and next steps.');else if(page==='notifications')simple('notifications','Notifications','Stay on top of new matches and activity.');else simple('support','Help & Support','Get help from the BidBidder team.')}
landing()
if(supabase){supabase.auth.getSession().then(r=>{if(r.data.session){user=r.data.session.user;page='dashboard';render()}})}
